name: flutter_finance
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.15.0+1
  google_sign_in: ^4.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/nulogo.png
    - assets/images/googleicon.png

